### ISSUE TITLE
table-layout: auto

### ISSUE THREAD

**Issue by goodoldneon** [offirgolan/ember-light-table#106]
First off, I love Ember Light Table! Much easier than manually creating tables.

I'd like my table to behave like it has the CSS attribute "table-layout: auto". In other words, column widths change to accommodate the width of their contents. But since Ember Light Table renders the table head as a separate table, "table-layout: auto" doesn't consider the width of the body data below.

For example, look at the "League" column (4th from the left). It's wider than the column since Ember Light Table makes all the columns the same width:
<img width="1010" alt="screen shot 2016-07-16 at 8 45 26 pm" src="https://cloud.githubusercontent.com/assets/20100586/16898078/b983c22c-4b96-11e6-8e16-f5d1cce8afc5.png">

When I give the head and body tables the "table-layout: auto" attribute, the columns become misaligned:
<img width="1006" alt="screen shot 2016-07-16 at 8 49 51 pm" src="https://cloud.githubusercontent.com/assets/20100586/16898083/eb938eb4-4b96-11e6-9bdd-a79e2e8b68e9.png">

**Comment by buschtoens** [comment]
`table-layout: auto` cannot be used due to the way we enable scrolling, as you already indicated. In my opinion this really is a shortcoming of HTML / CSS. Do a quick Google search for scrollable tables and you won't find a satisfying solution with dynamically sized columns.

`table-layout: auto` is quite slow for big tables anyway. I'd suggest we improve on the already existing `width` property of the `Column` class. Currently the value is transparently passed through to the HTML `width` attribute, which is deprecated in HTML5 and is limited to pixel values (at least in Chrome).

Two possible ideas:

- Pass the `width` property to an inline style attribute (`style="width: {{width}}"`) to enable all sizing units.
- Build a more elaborate sizing system using Flex Box and disable the default browser table layout completely.

**Comment by offirgolan** [comment]
@buschtoens a PR is always welcomed 😜

**Comment by buschtoens** [comment]
@offirgolan What [browser compatibility range](http://caniuse.com/#feat=flexbox) do you strive for? The flexbox implementation in IE11 is workable but has some considerable bugs [as outlined here](https://github.com/philipwalton/flexbugs).

I haven't given this any deeper thought yet, but I'll try to cook something up that works in IE11.

**Comment by offirgolan** [comment]
> Pass the width property to an inline style attribute (style="width: {{width}}") to enable all sizing units.

I think this will be an easy solution as of right now. 

> Build a more elaborate sizing system using flexbox and disable the default browser table layout completely.

I would love to see this solution in action @buschtoens but that will take much more time and will need to be discussed further. If you have time to put 

If you're up to it, can you handle the first solution as an intermediate fix?

**Comment by offirgolan** [comment]
Resolved with #163 via using `style="width: {{width}}"` instead of `width="{{width}}"`
