### ISSUE TITLE
onScrolledToBottom called just once.

### ISSUE THREAD

**Issue by betaSocialCode** [offirgolan/ember-light-table#108]
Thank you for sharing your addon.
In my implementation, which is basically a copy of the example at http://offirgolan.github.io/ember-light-table/, "onScrolledToBottom" is called just once when the component first loads, but it doesn't get called again on scroll (although "canLoadMore" is true after the first fetch of records). 
Are there any more configurations needed for the infinite scroll to work?
I didn't see any in the example or docs.
Thank you very much!

**Comment by buschtoens** [comment]
`onScrolledToBottom` should be called irregardless of `canLoadMore`. The action originates [here](https://github.com/offirgolan/ember-light-table/blob/master/addon/components/lt-infinity.js#L26) and is propagated through the body to your controller / component.

You have to implement the `canLoadMore` behavior yourself, as it is done in the example:

```js
onScrolledToBottom() {
  if(this.get('canLoadMore')) {
    this.incrementProperty('page');
    this.fetchRecords();
  }
}
```

Having said that, are you sure that `onScrolledToBottom` is only called once? It should be called every time the [`{{lt-infinity}}`](https://github.com/offirgolan/ember-light-table/blob/c8cf285002e11772cf45521c273b8eb02b9243fa/addon/templates/components/lt-body.hbs#L38) component scrolls into the viewport.

Can you maybe share your code so we can step through it? :)

**Comment by betaSocialCode** [comment]
@buschtoens thanks for your response. That was my understanding. My code is here: https://gist.github.com/betaSocialCode/1d5703746a096ccec8f571ec84745151
Thanks again!

**Comment by buschtoens** [comment]
Sorry for being so persistent, but sometimes it's just the most trivial stuff going wrong. Did you add a `console.log('pizza');` right [in line 102](https://gist.github.com/betaSocialCode/1d5703746a096ccec8f571ec84745151#file-turbo-data-table-js-L102) to verify that `onScrolledToBottom` *actually* isn't called again?

If so, something with [`lt-infinity`](https://github.com/offirgolan/ember-light-table/blob/c8cf285002e11772cf45521c273b8eb02b9243fa/addon/components/lt-infinity.js) has to be going wrong. Maybe play around with the `scrollBuffer`? Are you doing anything funky with CSS?

Can you maybe isolate a complete working (or not working for that matter :smile: ) example in a repository? Otherwise it's pretty much impossible for us to track this bug down. :)

**Comment by betaSocialCode** [comment]
I sure did try to consol.log. onScrolledToBottom is definitely not called again. I'll look into it more or create an example you can step through. Thanks!

**Comment by offirgolan** [comment]
@betaSocialCode if you are able to create a simple reproduction app, please share it here and Ill look into it more. 

Also, are you on version 1.x?

**Comment by betaSocialCode** [comment]
@offirgolan , yeah, I'm on 1.0.1. Thanks!
