### ISSUE TITLE
Add css selectors for lines and cells

### ISSUE THREAD

**Issue by GCorbel** [offirgolan/ember-light-table#111]
It can be useful to add css selectors to help to find a row or a cell. The row can have this `#model-1.model` and a row can be found with `.attr`. So, to find a cell, I can do something like `$('#user-1 .name') ` to find the cell. It would be easier for styling and acceptance testing.

If we use EmberData, I think `row.content.constuctor.name`  and `row.content.id` is enough to find the row id but I'm not sure for non-EmberData resources.

What you think?

**Comment by taras** [comment]
Usually, when I write acceptance or integration tests, I use content of the cell to identify the cell. For example, you could do something like `$('td:content(Offir)')`. This reads much better in tests and your tests will be more resilient to change. I would recommend that you take this approach rather than adding classes to elements that are bound to data.

**Comment by offirgolan** [comment]
Im gonna go ahead and close this issue. Feel free to reopen if needed.
