### ISSUE TITLE
Fixed header without specifying height

### ISSUE THREAD

**Issue by bakerac4** [offirgolan/ember-light-table#126]
Was wondering if you guys would take a pull request regarding having a fixed header that uses the page's scroll bar.

I realize that I can do this myself in the table component template by using an addon like https://www.npmjs.com/package/ember-pin and doing something like 
```
{{#pinned-content top=0}}
    {{t.head renderInPlace=true}}
{{/pinned-content}}
```

But it seems strange that you get an error if you specify t.head as fixed and don't provide a height when I think you could handle both situations. 

Just wanted to hear your thoughts?

**Comment by offirgolan** [comment]
@bakerac4 sorry for a delayed response! 

Im sorry to say that using something like `ember-pin` would not suffice due to the use necessity of `ember-scrollable` form scrollbar emulation. Fortunately, this table is using flexbox! If you wrap the table in a stretchable flexbox container and allow it to grow, it can easily take up the rest of the available viewport. Doing that you can set the table height to `auto`. I feel like something like this should be in the demo... once I have some time ill add it in there 😄 

Please note that the table height property accepts a **string** and can be passed any unit (including `vh`)

**Comment by offirgolan** [comment]
Im gonna go ahead and close this issue. Feel free to reopen if needed.

**Comment by roberkules** [comment]
+1 for adding a demo.

still figthing it, applying `auto` alone doesn't work... the tbody just disappears, leaving only the thead visible. trying to play around with the flexbox container as you mentioned, but a demo would definitely help.

**Comment by erose** [comment]
@offirgolan I am also struggling with this and would appreciate a demo.
