### ISSUE TITLE
Loading template breaks sorting

### ISSUE THREAD

**Issue by rwwagner90** [offirgolan/ember-light-table#137]
I added some loading.hbs templates to my app, to take advantage of the built in loading stuff Ember provides, while resolving model hooks, and it seems to no longer be able to sort. I think this is because it removes the component from view, so it can't set the sort direction and stuff. Thoughts on how to resolve this?

**Comment by offirgolan** [comment]
@rwwagner90 are you creating a new table instance every time the component is reloaded? Im assuming this issue lies in the realm of keeping your current table state even after your move in and out of a loading state. 

The best and simplest solution I have found is keeping your table definition in a single file.

```js
// app/tables/my-table.js
export default new Table([...], [...]);
```

Now when you do this:

```js
// app/components/my-component
import myTable from '../tables/my-table';
export default Ember.Component.extend({
  table: myTable,
  init() {
    // do stuff here to add rows / columns / etc.
  }
});
```

Even when the component gets destroyed / initialize / etc. myTable will always be the same instance so sorting / column changes / etc will propagate throughout your app. In other words, it creates a **singleton** table instance.

**Comment by offirgolan** [comment]
@rwwagner90 Im gonna go ahead and close this issue as it has been abandoned.
