### ISSUE TITLE
Two columns resizing at the same time

### ISSUE THREAD

**Issue by HenryVonfire** [offirgolan/ember-light-table#139]
In the actual [example](http://offirgolan.github.io/ember-light-table/#/resizable), if you try to resize `State` (grabbing from the left of `Country`), both `State` and `Country` move in opposite directions. If you resize any other column, this behaviour disappear.

**Comment by offirgolan** [comment]
@HenryVonfire that is because both Country and State initially have a set width. When you resize State, it assigns it a width value which forces the Country column to adjust its own width depending on the size remaining in the table. This doesnt happen to all the columns because a majority of them have an initial set width.

**Comment by HenryVonfire** [comment]
If that's the case, why it's behaviour changes after resizing another column? shouldn't it do always the same?

**Comment by offirgolan** [comment]
> why its behaviour changes after resizing another column

When a column isnt given a width, it adapts and stretches to its available width. When you resize it, it gets forced a new fixed with which causes all other columns without a set width to resize themselves.

**Comment by HenryVonfire** [comment]
That's clear now, thanks for your explanation!

**Comment by offirgolan** [comment]
@HenryVonfire np! 😸
