### ISSUE TITLE
ember-wormhole vs ember-elsewhere

### ISSUE THREAD

**Issue by pjcarly** [offirgolan/ember-light-table#154]
Hi,

I recently came across this addon: https://github.com/ef4/ember-elsewhere

and was wondering if it isn't a better alternative than ember-wormhole, considering only public API is used, and the parts of the table rendered on different position all happen inside the same Ember Application already.

**Comment by offirgolan** [comment]
@pjcarly this is the first time I've heard of ember-elsewhere. I'll have to check it out and see if it fulfills all of our current requirements 😸

**Comment by pjcarly** [comment]
@offirgolan aces! Let me know if there is anything I can do!

**Comment by offirgolan** [comment]
@ef4 are there any performance improvements in using ember-elsewhere over ember-wormhole?

**Comment by ef4** [comment]
I don't expect a performance difference. I do generally recommend ember-elsewhere when you're targeting somewhere far away that's still within an Ember app. 

That said, until Ember gets an official block capture API, ember-elsewhere does not support block-form invocation. Users would need to define components for their header and footer, instead of inline blocks. 

At which point you don't really need ember-elsewhere anyway, you could just render those component directly. That is the boring-but-reliable solution for an addon like this one, so:

```hbs
{{#light-table table as |t|}}
  {{#t.head onColumnClick=(action 'sortByColumn') as |groups subColumns table|}}
    {{#each groups as |group|}}
      {{!-- ... --}}
    {{/each}}
  {{/t.head}}
{{/light-table}}
```

becomes

```hbs
{{#light-table table head=(component "my-head" onColumnClick=(action 'sortByColumn') as |t|}}
{{/light-table}}
```

```hbs
{{! my-head.hbs }}
{{#each groups as |group|}}
   {{!-- ... --}}
{{/each}}
```

Notice that argumnts like onColumnClick can still go in just the same, and block params like `group` can become regular parameters that are set on the child component. In this case, light-table's own template would include:

```hbs
{{#if head}}
  {{component head groups=groups subColumns=subColumns table=this}}
{{else}}
  {{!- the default header goes here -}}
{{/if}}
```

**Comment by offirgolan** [comment]
@ef4 thank you for the quick feedback! I believe your insight on this issue is substantial enough to close this. In the world of ember-light-table, I dont think that we currently want to modify the public API that has been exposed since the initial release. 

As a side note, I think that ember-elsewhere looks fairly promising! Awesome work 😸

I'll be keeping an eye on alternate implementations that can be more optimal yet still meet our requirements.
