### ISSUE TITLE
Format returning HTML, valuePath being a function or defining cell components in the same file

### ISSUE THREAD

**Issue by rstudner** [offirgolan/ember-light-table#233]
Just trying to think of a way to not general lots of "public"? components for tables.

a) if format could return html (think adding font awesome icons) that'd be sweet.
b) if valuepath could be a function (then technically I guess there wouldn't need to be format)
c) Can something like this work (partially an Ember question):
```
import Ember from 'ember';
import Table from 'ember-light-table';
import hbs from 'htmlbars-inline-precompile';

const {computed} = Ember;

const StatusComponent = Ember.Component.extend({
  layout: hbs`
      <h4>Hi!</h4>
    `
});

export default Ember.Component.extend({
  page: 1,
  limit: 20,
  dir: 'asc',
  sort: null,
  model: null,
  isLoading: false,
  canLoadMore: true,

  columns: computed(function() {
    return [{
      label: 'Name',
      sortable: true,
      valuePath: 'displayName',
      width: '20%',
    }, {
      label: 'Status',
      cellComponent: StatusComponent,
      width: '15%'
    }, {
      label: 'Actions',
      sortable: false,
      width: '10%'
    }];
  }),

  table: computed('model', function() {
    return new Table(this.get('columns'), this.get('model'), {enableSync: true});
  })
});
```

The above, if I try to do it, shows me:
ember.debug.js:16416 Uncaught TypeError: key.indexOf is not a function

i've tried exporting the StatusComponent as well, but didn't change the error.

**Comment by offirgolan** [comment]
Hi there,

a) if format could return html (think adding font awesome icons) that'd be sweet.

This should be possible.

```js
{
  valuePath: 'foo',
  format(value) {
    return Ember.String.htmlSafe('<h1>' + value + '</h1>'); 
  }
}
```
b) if valuepath could be a function (then technically I guess there wouldn't need to be format)

`valuePath` is two-way bound. If you change it via column.set('valuePath', 'bar'), the cell should rerender. 

c) Can something like this work (partially an Ember question):

This is bad practice and I dont suggest doing something like this. Also, this isnt supported since `cellComponent` must be a string.

I suggest going with option **a** 😸

**Comment by rstudner** [comment]
Thanks very muchly! :)

**Comment by offirgolan** [comment]
@rstudner feel free to reopen if it didnt work out.
