### ISSUE TITLE
onScrolledToBottom will not stop firing

### ISSUE THREAD

**Issue by Vatosteve** [offirgolan/ember-light-table#280]
Replicating the examples in the documentaion, onScrolledToBottom is continuously fired without scrolling to the bottom. This is causing all data in the data set to be loaded automatically rather than on actually scrolling to the bottom.

This has worked previously on 1.3.1, but any version past that exhibits the same behavior.

I am no longer able to run 1.3.1 either as there seems to be dependency errors.

**Comment by offirgolan** [comment]
Hi @Vatosteve, I've been testing this table across multiple production application with no such issue. Can you give me some more details on your dev + ember env and also some code snippets?

**Comment by Vatosteve** [comment]
Thanks for looking.

I have it repeating on one project consistently, but at the same time I have another where the issue doesn't occur. Instead of wasting your time I'll try to determine the difference, but so far I don't anything unusual between the two. If I find an answer, I'll update this.

**Comment by offirgolan** [comment]
Sounds like a plan 😄.

**Comment by tibibud** [comment]
I have a similar issue, but I can trace it back to my workaround.
Since ember-scrollable does not support horizontal scrolling I made a container that has a fixed width for the table. This container has overflow-x: auto; It obviously works, but since upgrading to the newer version, the onScrolledToBottom() keeps firing even when I scroll horizontally. This is probably due to the transition to ember-in-viewport as opposed to the other strategy (where you would select window as a scroll target).

Is there a solution for this? Horizontal scrolling is unfortunately important for us.

Thanks for taking the time to make this amazing addon!

**Comment by offirgolan** [comment]
@tibibud are you on the latest version of ELT? The latest version includes a rudimentary horizontal scrolling solution 😄

**Comment by tibibud** [comment]
I will try to migrate to it. If it stops onScrolledToBottom() from firing on horizontal scroll, then it will be useful for us. I will keep you posted.

**Comment by tibibud** [comment]
Unfortunately, even with build 1.0.7 and the "built-in" overflow I get the same phenomenon. The onScrolledToBottom() is called when horizontally scrolling. I have the fixed table flag set to true, not sure if that influences anything. Is there something wrong with my config.

@offirgolan Could you reproduce this?

**Comment by offirgolan** [comment]
@tibibud I'm not able to recreate this issue with the demo app. Everything seems to be normal.

![elt-horizontal-scroll](https://cloud.githubusercontent.com/assets/575938/21131864/ec6ca5e6-c175-11e6-8380-ec08486ebcdc.gif)

**Comment by Vatosteve** [comment]
@offirgolan So, I figured out what was causing the onScrolledToBottom to fire. I was using

`this.get('table').setRows`

Instead of 

`this.get('table').addRows`

Which seems to be causing the onScrolled to bottom to fire every time the setRows is called. I don't know if that is intended behaviour or not, but definitely an issue in my logic.

Thank you!
