### ISSUE TITLE
basic sorting implementation

### ISSUE THREAD

**Issue by jamesdixon** [offirgolan/ember-light-table#288]
Hi,

First, I'm probably missing something very obvious, but I've spent too much time on this, so I figured I'd ask for help :)

I'm just trying to implement a basic local sort using `computed.sort`. The table initially has no records. After selecting a date range from a calendar, it then calls `fetchRecords`. I can see the data loading, but no rows are displayed. If I change:

`let table = new Table(this.get('columns'), this.get('sortedModel'), { enableSync: true });`

to

`let table = new Table(this.get('columns'), this.get('model'), { enableSync: true });`

the records appear as expected.

Here's a more complete version of the code:

```js
import Ember from 'ember';
import Table from 'ember-light-table';
import { task, timeout } from 'ember-concurrency';

const { A, Component, computed, inject, isEmpty } = Ember;

export default Component.extend({
  store: inject.service(),
  time: inject.service(),

  table: null,
  model: null,

  sortBy: ['staff.lastName'],

  sortedModel: computed.sort('model', 'sortBy'),

  columns: [
    {
      label: 'First Name',
      valuePath: 'staff.firstName',
      width: '20%'
    },
    {
      label: 'Last Name',
      valuePath: 'staff.lastName',
      width: '20%'
    },
    {
      cellComponent: 'currency-formatter',
      label: 'Total',
      valuePath: 'total',
      width: '20%'
    },
    {
      cellComponent: 'table-row-chevron',
      width: '40%'
    }
  ],

  init() {
    this._super(...arguments);

    this.set('model', A([]));
    this.set('filter', {
      start: null,
      end: null
    });

    let table = new Table(this.get('columns'), this.get('sortedModel'), { enableSync: true });
    this.set('table', table);

    let sortColumn = table.get('allColumns').findBy('valuePath', this.get('sortBy'));

    // Setup initial sort column
    if (sortColumn) {
      sortColumn.set('sorted', true);
    }
  },

  /**
   * Fetches records from the API.
   * @protected
   */
  fetchRecords: task(function* () {
    yield timeout(400);

    const params = {
      filter: this.get('filter')
    };

    const records = yield this.get('store').query('pay-stub', params);
    this.get('model').pushObjects(records.toArray());

  }).restartable(),
```

Am I missing how `enableSync` behaves?

Thank you!

**Comment by offirgolan** [comment]
@jamesdixon I think your issue is `computed.sort('model', 'sortBy')` which (I believe) returns a new array instance every time. `enableSync` only works when you are changing the passed array instance. Since every time there is a change in the model, the CP returns a new instance which is fine if you are just observer the property. The table isnt observing the CP, its observing changes on the passed instance. Can you verify if this is the case?

**Comment by dknutsen** [comment]
@jamesdixon @offirgolan yeah I ran into the same thing. I ended up having to clear the (separate) array that ELT is observing and load records into it based on the results of the sort.

**Comment by rwwagner90** [comment]
@offirgolan could we have ELT go ahead and rerender when a fully new array is passed as well?

**Comment by jamesdixon** [comment]
@offirgolan that does seem to be the case. Given that I'm not doing any pagination on this particular record set, I've just disabled `enableSync` and then did the following:

```js
  fetchRecords: task(function* () {
    yield timeout(400);

    const params = {
      filter: this.get('filter')
    };

    const records = yield this.get('store').query('pay-stub', params);
    this.get('table').setRows(this.get('sortedModel'));

  }).restartable(),
```

That said, I'm wondering if it would be good to show an example of this somewhere in the docs for those who aren't doing any sort of server-side manipulation of the records. Thoughts?

**Comment by offirgolan** [comment]
> could we have ELT go ahead and rerender when a fully new array is passed as well?

I dont think thats a good idea nor do I know if I want to go that route. The point of `enableSync` is that it keeps two arrays in sync. The passed data instance, the table's rows instance. If the data instance is not constant, then you shouldnt really be using enableSync 😄 

@jamesdixon I think your alt solution is solid. Thats the way I've done it in multiple apps. 

> That said, I'm wondering if it would be good to show an example of this somewhere in the docs for those who aren't doing any sort of server-side manipulation of the records.

I'm not really sure we can do that in the current demo app. Sort needs to happen server side since the data is paginated and exists on the mock server. Maybe we can include a small example of sorting in the docs but I'm not really sure where that would go either. Maybe in a cookbook sort of page / module?

**Comment by jamesdixon** [comment]
@offirgolan a "cookbook"-type page is exactly what I was thinking originally. Sort of like is done on the Ember Power Select site.

**Comment by offirgolan** [comment]
@jamesdixon the docs use yuidoc so the cookbook will have to be in some file in the code base, which kinda sucks, but I think a cookbook type page would deem pretty useful. I'll take a look into this and see what I can do. 

Im gonna make a new issue for it and add this task to it.

**Comment by offirgolan** [comment]
@jamesdixon cookbook page is now live 😄 !
