### ISSUE TITLE
thead, tbody and tfoot in separate table tags

### ISSUE THREAD

**Issue by chilicoder** [offirgolan/ember-light-table#337]
I'm trying to produce minimal working example using `ember-light-table`
Somehow `thead`, `tbody` and `tfoot` renders in separate `table` tags
<img width="526" alt="screen shot 2017-02-13 at 18 05 44" src="https://cloud.githubusercontent.com/assets/3491833/22893958/8f1de062-f217-11e6-820b-5b33080903e0.png">
here is the link for repo: https://github.com/chilicoder/ember-light-table-example

at the same time tables in document site renders in one table. 

Can you please show where I'm wrong?

PS My Ember version in 2.11

**Comment by offirgolan** [comment]
@chilicoder that is intended behavior. What exactly is the problem you're having?

**Comment by chilicoder** [comment]
now i have 3 different `table` tags. And it should be one. Smth like
```
<table>
<thead>
</thead>
<tbody>
</tbody>
<tfoot>
</tfoot>
</table>
```

**Comment by SlyDen** [comment]
@chilicoder believe it shouldn't be one table ... just because you want fixed (sticky) header and\or footer ... with horizontal scrolling maybe and in the end you'll come to the solution with separate tables for header, body and footer (the only reliable solution nowadays ...)

**Comment by sergafts** [comment]
I have run into this too. My only issue (this far) is that I cannot style using bootstrap. If set `tableClassNames` to e.g `table table-hover`, bootstrap treats every separate `<table>` element as a different table. 

This means that if you set `tableClassNames` on the `{{light-table}}` component, you will have a weird spacing after the header (see attached image) and whatever else bootstrap uses on the last row of a table & after the table. 
If you set `tableClassNames` on the `{{table.body}}` component, you need to style the header manually. 

Not sure if this is an issue or expected behaviour, I was led here from a google search & I thought my experience might help
![screenshot from 2017-02-28 12-44-38](https://cloud.githubusercontent.com/assets/14074326/23402470/5ecaac94-fdb4-11e6-92bc-618b14cb297d.png)

**Comment by chilicoder** [comment]
> My only issue (this far) is that I cannot style using bootstrap.
Same for me

I don't need fixed columns and horizontal scrolling (I think it is possible to implement this without having 3 table tags, but I did zero research on it), but I need to style the table using bootstrap theme.

anyway, looks like it is not the bug, but a feature. Because I saw the same in examples.

**Comment by offirgolan** [comment]
> If set tableClassNames to e.g table table-hover, bootstrap treats every separate table element as a different table. This means that if you set tableClassNames on the {{light-table}} component, you will have a weird spacing after the header

I think some basic custom CSS targeting `.ember-light-table table` will resolve your issue here.

As of right now, the best current solution to support all the requested features is unfortunately using the 3 table method.
