### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Elisabethask** [offirgolan/ember-light-table#361]
Hi, 

I want to change the CSS in this example, but I'm not a developer, I'm a UX - desginer so this is all new to me. How do i find the css code i your example so that i edit it? 

Br, 
Elisabeth

**Comment by taras** [comment]
Can you provide a bit of context on what you're trying to do so we can suggest the best way for you to accomplish your goal?

**Comment by Elisabethask** [comment]
I want to redesign the column, the rows and the cells. So I need o know where to find the classes for these.

**Comment by taras** [comment]
Ok, I want to make sure I understand. Please, let me know if I got any of this wrong:

You're working on a project where a developer installed `ember-light-table`. You would like to change how the table looks in your application. Typically, customising existing CSS is the process of overloading the provided CSS but in your case you would prefer to change the CSS classes that are provided by `ember-light-table`.

Did I understand you correctly?

**Comment by Elisabethask** [comment]
Yes :)

**Comment by taras** [comment]
I'm not sure about this 100% because it's unusual for me to want to overload Ember Light Table's CSS without just using CSS to overload the styles. Try creating a file in your application's styles directory called `ember-light-table.css`. This should take priority over the files that's provided by the addon.

In summary, create a file at path `app/styles/ember-light-table.css`. You and copy and paste parts of the original CSS from https://github.com/offirgolan/ember-light-table/blob/master/addon/styles/addon.css

Let me know if this works.

**Comment by offirgolan** [comment]
Closing as this issue has been abandoned. Feel free to reopen if needed.
