### ISSUE TITLE
Processing more than one array / aggregate data

### ISSUE THREAD

**Issue by anees-tricon** [offirgolan/ember-light-table#405]
Firstly, Thanks a lot for this wonderful Addon

Am trying to render a table, where first two columns have a checkbox. So i a passing Three different Arrays into my component. `users`,`selected` and `bookmarked`. So what i basically want is, the particular row should have the checkboxes checked if the `users` instance of that row is in the `selected` or `bookmarked` row.

Since am passing the `users` as the rows for the Table constructor, i am not able to fetch the other two arrays in the cellComponent. So i think 'serialze...` methods should do the job for me. 
Any suggestions or exampels?

**Comment by buschtoens** [comment]
> Firstly, Thanks a lot for this wonderful Addon

Glad you like it! :smile: 

> Since am passing the users as the rows for the Table constructor, i am not able to fetch the other two arrays in the cellComponent. So i think 'serialze...` methods should do the job for me.
Any suggestions or exampels?

`serializeContentObjects` and `serializeSyncArrayObjects` are private API and protected (or "abstract") methods of the [`SyncArrayProxy`](https://github.com/offirgolan/ember-light-table/blob/867b9803667c16842773c28bda6557afbcac1495/addon/-private/sync-array-proxy.js#L50-L68) that are overridden (or "implemented") in the [`RowSyncArrayProxy`](https://github.com/offirgolan/ember-light-table/blob/867b9803667c16842773c28bda6557afbcac1495/addon/classes/Table.js#L15-L23).

A `RowSyncArrayProxy` is internally used by `Table` if you [`enableSync`](https://offirgolan.github.io/ember-light-table/docs/classes/Table.html) to wrap the objects passed as rows into actual `Row` instances.

You can't hook into that and should not use it for this kind of aggregation.

But to answer your original question: There are two solutions I can think of.

#### Aggregate data in JS land

```js
export default Component.extend({
  users: [],
  selected: [],
  bookmarked: [],

  rows: computed('users.[]', 'selected.[]', 'bookmarked.[]', function() {
    const users = get(this, 'users');
    const selected = get(this, 'selected');
    const bookmarked = get(this, 'bookmarked');

    return users.map(user => ({
      user,
      isSelected:   selected.includes(user),
      isBookmarked: bookmarked.includes(user)
    }));
  }),

  columns: computed(() => [
    {
      label: 'Selected?',
      valuePath: 'isSelected',
      cellCompponent: 'cell-checkbox'
    },
    {
      label: 'Bookmarked?',
      valuePath: 'isBookmarked',
      cellCompponent: 'cell-checkbox'
    },
    {
      label: 'Name',
      valuePath: 'user.name'
    }
  ])
});
```

Depending on how big `selected` and `bookmarked` are, this setup can become quite inefficient.

#### Aggregate data in components

[Here](https://github.com/offirgolan/ember-light-table/blob/867b9803667c16842773c28bda6557afbcac1495/addon/templates/components/cells/base.hbs#L2) you can see all parameters passed to a `cellComponent`:

```hbs
{{!-- addon/templates/components/cells/base.hbs --}}
{{#if column.cellComponent}}
  {{component column.cellComponent tableActions=tableActions table=table column=column row=row value=value rawValue=rawValue}}
{{else}}
  {{value}}
{{/if}}
```

Either you abuse `tableActions` or `table` to include `selected` and `bookmaked`, so that you can access these arrays in the `cellComponent`, or you [pass a curried component](https://www.emberjs.com/api/classes/Ember.Templates.helpers.html#toc_nested-usage) as the `cellComponent`.

For that you would have to curry your `cellComponent` in JS land, of which I'm not certain that it's possible, or pass it into your main table component and declare your columns array in dependence of it.

```js
// components/user-table.js
export default Component.extend({
  users: [],
  selectedComponent: null,
  bookmarkedComponent: null,

  columns: computed('selectedComponent', 'bookmarkedComponent', () => [
    {
      label: 'Selected?',
      cellCompponent: get(this, 'selectedComponent')
    },
    {
      label: 'Bookmarked?',
      cellCompponent: get(this, 'selectedComponent')
    },
    {
      label: 'Name',
      valuePath: 'name'
    }
  ])
});
```

```hbs
{{user-table
  users=users
  selectedComponent=(component "cell-checkbox" lookup=selected)
  bookmarkedComponent=(component "cell-checkbox" lookup=bookmarked)
}}
```

```js
// components/cell-checkbox.js
export default Component.extend({
  row: null,
  lookup: [],

  isEnabled: computed('row', 'lookup.[]', () => get(this, 'lookup').includes(row))
});
```

**Comment by buschtoens** [comment]
IMHO you're safest bet is abusing [`tableActions`](https://offirgolan.github.io/ember-light-table/docs/classes/light-table.html#property_tableActions) as a shared object containing `selected` and `bookmarked`.

**Comment by buschtoens** [comment]
Another option is using Array Observers. Without shifting the constraints, you'd probably get the best performance by watching the `selected` and `bookmarked` arrays and upon mutation set the `isSelected` and `isBookmarked` properties on the `table.rows` array.

However Observers are frowned upon as they almost always are a symptom of a poor data structure / data flow choice as it is with this case.

Of course I don't know how you're getting your data, but I would recommend merging all three arrays into one, similar to the one shown in **Aggregate data in JS land**, instead of managing three separate arrays. You'd do that right where you're fetching the data.

This way you have all state in one place and don't need to iterate multiple times over multiple arrays to derive it.

This isn't really a problem of or exclusive to ember-light-table. Maybe we should write up some guides for scenarios like this one. :thinking:

**Comment by buschtoens** [comment]
#457 now adds a standard way for accessing additional data in components.
