### ISSUE TITLE
[IE <= 10] Column, Row, Table: static properties (reopen, ...) not inherited

### ISSUE THREAD

**Issue by mastastealth** [offirgolan/ember-light-table#436]
I have a component using the table that does a little bit of customizations via reopen. Oddly enough, only 2 of the 10 seem to fail. I get a:
`TypeError: Object doesn't support property or method 'reopen'` 
...in IE10 for `TableHeaderMixin` and `ColumnClass` (though disabling `ColumnClass` makes the other work, so I think it is the maint culprit). 

However, `reopen`ing `LightTable`, `Header`, `Footer`, `Row`, `Column`, `Cell`, and `SortableObjects` works just fine. Firefox reopens all of them too, so is there anything in particular I should know about `ColumnClass` giving errors? 🤔 

As an example, when I have IE10 console log the `ColumnClass` for me (before reopening) it returns:
```
function Column() {
      var options = arguments.length <= 0 || arguments[0] === undefined ? {} : arguments[0];

      _classCallCheck(this, Column);

      if (options instanceof Column) {
        return options;
      }

      _get(Object.getPrototypeOf(Column.prototype), 'constructor', this).call(this);
      this.setProperties(options);

      var subColumns = options.subColumns;

      subColumns = emberArray(makeArray(subColumns).map(function (sc) {
        return new Column(sc);
      }));
      subColumns.setEach('parent', this);

      this.set('subColumns', subColumns);
    } 
```

which seems to be the correct function. Unfortunately I tried to get a twiddle of this, but ember-twiddle doesn't work on IE10 either! 😅

**Comment by buschtoens** [comment]
Thank you for reporting this issue! I was able to reproduce it in IE10 and IE9 as well.

> ...in IE10 for TableHeaderMixin and ColumnClass (though disabling ColumnClass makes the other work, so I think it is the maint culprit).

Your assessment is correct. `Column` is the only class that cannot be reopened. If I'm not missing some weird edge case, `TableHeaderMixin` can be reopened just fine. You probably just confused some errors, but please do correct me, if I'm wrong.

Furthermore, I have found that all three [`classes`](https://github.com/offirgolan/ember-light-table/tree/master/addon/classes) files (and only these) are problematic:

- [`Column`](https://github.com/offirgolan/ember-light-table/tree/867b9803667c16842773c28bda6557afbcac1495/addon/classes/Column.js)
- [`Row`](https://github.com/offirgolan/ember-light-table/tree/867b9803667c16842773c28bda6557afbcac1495/addon/classes/Row.js)
- [`Table`](https://github.com/offirgolan/ember-light-table/tree/867b9803667c16842773c28bda6557afbcac1495/addon/classes/Table.js)

This makes sense, as all three share the same specialty: they are "real" ES6 classes intermingled with `EmberObject`s:

```js
export default class Column extends EmberObject.extend({
  // ..
}) {
  constructor() {
    // ...
  }
}
```

I'm gonna work off of that assumption, but would love it, if you could verify or disprove that.

**Comment by buschtoens** [comment]
I'm pretty sure, that I've identified the error. The prototype chain isn't set up correctly. I would argue, that this is due to IE10 not supporting [`__proto__`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/proto). But I'll have to investigate further.

#### IE10

![image](https://user-images.githubusercontent.com/834636/27395753-282b1fe2-56b1-11e7-9e8a-c22601b5708a.png)

#### IE11

![image](https://user-images.githubusercontent.com/834636/27395782-454d174c-56b1-11e7-9aea-91afb6082cf2.png)

**Comment by buschtoens** [comment]
https://babeljs.io/docs/usage/caveats/#internet-explorer-classes-10-and-below-

**Comment by buschtoens** [comment]
I don't really see a reason, why these three classes were implemented in such a way, but it's been so [right from the beginning](https://github.com/offirgolan/ember-light-table/commit/a2ffbdb07c77866169fd87e7936f732a921b351b#diff-69ccb0cc4aa0c12c353391890da5a4b2). Most likely to enable using [`new Column(options)`](https://github.com/offirgolan/ember-light-table/blob/v1.8.6/addon/classes/Table.js#L413) instead of `Column.create(options)`. Same goes for `Row` and `Table`.

The cleanest fix is discarding the ES6 magic and exclusively using good ol' `EmberObject`s. However that would break all apps.

Alternatively we could either:

- Statically assign properties like `reopen`. Basically what [protoToAssign](https://babeljs.io/docs/plugins/transform-proto-to-assign/) does. Maybe we ca even use that transform on these files. This will likely penalize performance.
- Attempt to somehow access the underlying `EmberObject` with some magic or explicitly expose it. However, this would require users to be aware of that quirk.

**Comment by buschtoens** [comment]
Third option: feature-detect `__proto__` support and only assign these properties if necessary.

**Comment by buschtoens** [comment]
If you use `(Column|Row|Table).prototype.reopen` it works in old IE and newer browsers.

```js
Table.prototype.reopen({
  getColumns() {
    return this.get('columns');
  }
});

const t = new Table([{ label: 'foo' }], []);
console.log(t.getColumns())
```

**Comment by buschtoens** [comment]
@alexander-alvarez We can either document this quirk as the official way going forward and call it a day or attempt to feature-detect and conditionally polyfill.

**Comment by buschtoens** [comment]
I'll give polyfilling a shot tomorrow and we'll see how it works out.

**Comment by buschtoens** [comment]
@mastastealth The issue has been resolved in `master`. It would be super nice of you, if you could give this a try with all sorts of `reopen`s and `reopenClass`es your heart desires. :blush: 

```shell
# if you're using yarn
yarn add offirgolan/ember-light-table#master

# or npm
npm install --save offirgolan/ember-light-table#master
```
