### ISSUE TITLE
Scrollable Container and preventing db queries

### ISSUE THREAD

**Issue by snewcomer** [offirgolan/ember-light-table#7]
Any thoughts on providing a hook for users to prevent calling the onScrolledToBottom method if they have already retrieved all their records from the db, or should this behavior be left up to the user?

**Comment by offirgolan** [comment]
I think this kind of behavior should be up to the user since the table acts only as a `view` so it will never really know when there is no more data. If the logic is pretty simple, you can have a condition in your `onScrolledToBottom ` action or you can use `ember-infinity` with this addon which should cover most use-cases.
