### ISSUE TITLE
yielding row

### ISSUE THREAD

**Issue by efx** [offirgolan/ember-light-table#8]
This is similar to #2. 
I have a few tables in an ember application that use a component for a row. Can light-table or one of the contextual components yield an individual or something like that? My use case is to customize the HTML of each row.
```hbs
{{#t.body as |body row|}}
{{my-row-component row=row}}
{{/t.body}} 
```
I would need to this to happen before the user clicks on a row, so `body.expanded-row` wouldn't apply. There doesn't seem to be a way to customize the HTML of the individual rows. I'm open to other ideas too.

**Comment by snewcomer** [comment]
cellComponent might help out, but not for the entire row...only for the individual column.  This allows the use of a component instead of just the model property.  I can see the use case where each individual component would need customization (i.e. multiple model properties, avatars, ect) and styling for the entire row can be targeted via the `lt-row` class.  I'm sure though that having access to the row is useful in other scenarios that I'm not thinking of.

https://github.com/offirgolan/ember-light-table/blob/feab5b45dadbbddb135cdf14da553c9fcfca1e38/tests/helpers/table-columns.js#L6

**Comment by efx** [comment]
thanks for pointing that out; I hadn't noticed that. I'll give that a whirl as it might resolve my specific case.

**Comment by offirgolan** [comment]
@snewcomer Thanks for helping out :smile_cat:. I can definitely see the need for this. When I have some free time Ill look more into this and see what I can do. 

@efx let me know if that solves your use-case!

**Comment by efx** [comment]
I'll close for now since I think `cellComponent` provides the flexibility I need.
